package com.riskguard.model;

public enum RiskCategory {
    INDEMNITY,
    LIMITATION_OF_LIABILITY,
    TERMINATION,
    CONFIDENTIALITY,
    IP_RIGHTS,
    GOVERNING_LAW,
    JURISDICTION,
    AUTO_RENEWAL,
    PAYMENT_TERMS,
    SLA,
    DATA_PROTECTION,
    INSURANCE_OBLIGATION,
    INTELLECTUAL_PROPERTY_TRANSFER,
    OTHER
}
