package com.riskguard.model;

public enum RiskCategory {
    INDEMNITY,
    LIMITATION_OF_LIABILITY,
    TERMINATION,
    CONFIDENTIALITY,
    IP_RIGHTS,
    GOVERNING_LAW,
    JURISDICTION,
    AUTO_RENEWAL,
    PAYMENT_TERMS,
    SLA,
    DATA_PROTECTION,
    INSURANCE_OBLIGATION,
    INTELLECTUAL_PROPERTY_TRANSFER,
    SCOPE_OF_WORK,
    CLAIMS_AND_DISPUTES,
    SITE_CONDITIONS,
    WARRANTIES,
    COMPLETION_AND_HANDOVER,
    LIABILITY,
    PERFORMANCE,
    OTHER
}
